import streamlit as st

#PARTS OF THIS app.py FILE CONTAINS CODE GENERATED BY CLAUDE SONNET 4.6. 
#ANYTHING GENERATED BY AI WILL BE LABELLED WITH COMMENTS AS "AI START" and "AI END"
#THIS IS TO INDICATE THE START AND END OF CODE GENERATED BY AI
#Please note, the appendix of my report will have the full prompt + output + how I used output for my own code


#Old app.py changed into pages/1_Simulation.py
#Current app.py is acting as home page now
st.set_page_config(
    page_title="A&E Decision Support Tool", page_icon="🏥", layout="wide"
)

st.title("A&E Discrete Event Simulation")
#AI START
st.caption("A decision-support tool for NHS emergency department staffing")
#AI END
st.markdown("---")

#Key metric cards
#AI START
st.subheader("The Challenge Facing NHS A&E Departments")
 
m1, m2, m3, m4 = st.columns(4)
m1.metric(
    label="4-Hour Target (2010)",
    value="94%",
    help="Percentage of A&E patients seen within 4 hours at its peak"
)
m2.metric(
    label="4-Hour Target (2024)",
    value="60%",
    delta="-34 pp",
    delta_color="red",
    help="Performance by the time of the Darzi review"
)
m3.metric(
    label="Simulation studies with real-world impact",
    value="14%",
    help="Syed Mohiuddin et al. (2017) — only 14% of OR/simulation projects led to implemented changes"
)
m4.metric(
    label="Prototype built on",
    value="UCLH data",
    help="Calibrated against real NHS performance metrics from University College London Hospitals"
)
 
st.markdown("---")
#AI END


col1, col2 = st.columns(2, gap="large")

with col1:
    st.markdown("""
    ### 🚨 The Problem
    
    A&E departments across the UK have been under large amounts of pressure. This is backed by an investigation led by Lord Ara Darzi
    which found that the percentage of patients seen with the NHS 4 hour target dropped from 94% to 60% (From 2010 to 2024)
    This 34% collapse is driven by rising demand, workforce pressures, and bed shortages
    
    Simulation models have been used in emergency departments before, but research shows that only around 
    14% of projects led to implemented operational changes (Syed Mohiuddin et al., 2017). A key reason is that models are not designed 
    with decision makers in mind and lack clear interpretation of outputs.
    """)

with col2:
#AI START
    st.markdown("### ✅ What This Tool Offers")
    features = [
        ("🔬", "Calibrated simulation", "Built on real UCLH data so baseline outputs reflect observed NHS performance."),
        ("🎛️", "Interactive scenario explorer", "Adjust doctor and nurse levels in real time and re-run the simulation instantly."),
        ("🤖", "Automated result interpretation", "Plain-English summaries explain what the numbers mean for patients and staff."),
        ("📊", "Side-by-side comparison", "Compare multiple staffing scenarios to identify the most effective configuration."),
    ]
    for icon, title, body in features:
        with st.container(border=True):
            st.markdown(f"**{icon} {title}**")
            st.caption(body)
 
st.markdown("---")
#AI END

#AI START
st.subheader("🗺️ How to Use This Tool")
 
nav1, nav2, nav3 = st.columns(3)
 
with nav1:
    with st.container(border=True):
        st.markdown("#### 1 · Simulation")
        st.markdown(
            "Adjust staffing levels (doctors, nurses) and run the "
            "DES model."
        )
 
with nav2:
    with st.container(border=True):
        st.markdown("#### 2 · Scenario Comparison")
        st.markdown(
            "Compare pre-defined or custom staffing scenarios side by side "
            "to understand trade-offs and identify bottlenecks."
        )
 
with nav3:
    with st.container(border=True):
        st.markdown("#### 3 · About")
        st.markdown(
            "Read about the methodology, data sources, modelling assumptions, "
            "and limitations of this prototype."
        )
 
st.markdown("")
st.page_link("pages/1_Simulation.py", label="Go to Simulation →", icon="▶️")
 
st.markdown("---")
#AI END

st.info(
    "This tool is a proof-of-concept prototype developed as a final-year "
    "Computer Science project at City St George's, University of London. "
    "It is not intended for real clinical decision-making.",
    icon="ℹ️"
)
