import streamlit as st

#PARTS OF THIS 3_About.py FILE CONTAINS CODE GENERATED BY CLAUDE SONNET 4.6. 
#ANYTHING GENERATED BY AI WILL BE LABELLED WITH COMMENTS AS "AI START" and "AI END"
#THIS IS TO INDICATE THE START AND END OF CODE GENERATED BY AI
#Please note, the appendix of my report will have the full prompt + output + how I used output for my own code

st.set_page_config(
    page_title="About - A&E DES", page_icon="🏥", layout="wide"
)

st.title("About this tool")
st.markdown("---")

#AI START
tab_results, tab_limitations, tab_methodology = st.tabs([
    "📊 Understanding the Results",
    "⚠️ Limitations",
    "🔬 Data & Methodology",
])
#AI END


#AI START
with tab_results:
    with st.container(border=True): #AI END

        st.markdown("### 🕓 4-Hour Breach Rate")
        st.markdown(
"""The 4 hour breach rate is the percentage of patients who waiting longer than 4 hours from arrival to either discharge/admission to a ward.

An independent review led by Lord Ara Darzi found that the rate had fallen from 94% compliance in 2010, to around 60% in 2024. Meaning 34% of patients now wait longer than 4 hours. 
                    
> **How to read this metric:** The simulation displays the percentage of
> patients who *breach* the target (i.e. wait **longer** than 4 hours).
> A **lower number is better**. If the simulation shows a breach rate
> **above 20%**, the department is considered to be under significant pressure.
> The dataset this simulation was calibrated against shows a baseline 
> breach rate of **19.9%**. The simulation baseline produces **21.6%**.
                    """)
    st.markdown("")

    #Doctor and Nurse Utilisation
    with st.container(border=True):
        st.markdown("### 👩‍⚕️ Doctor and Nurse Utilisation")
        st.markdown("""
        Utilisation measures what percentage of time each resource is actively busy with a patient.
                    
        Having high doctor utilisation with low nurse utilisation (or vice verse) shows a bottleneck
        """)
        #AI START
        st.markdown("#### Utilisation bands")
 
        col_band, col_meaning = st.columns([1, 3])
        bands = [
            ("🟢 Below 70%",   "Staff have comfortable capacity. The department can absorb unexpected surges without significant impact on waiting times."),
            ("🟡 70 - 85%",    "Staff are productively busy. The system is running efficiently but starting to feel pressure at peak hours."),
            ("🟠 85 - 90%",    "The system is under significant pressure. Very little capacity exists to absorb surges — a busier-than-average hour can cause waits to spike rapidly."),
            ("🔴 Above 90%",   "Staff are critically overloaded. Long waits are near-certain and the breach rate will be high."),
        ]
        with col_band:
            for label, _ in bands:
                st.markdown(f"**{label}**")
                st.markdown("")
        with col_meaning:
            for _, meaning in bands:
                st.markdown(meaning)
                st.markdown("")
        #AI END

        st.markdown("")

    with st.container(border=True):

        st.markdown("### ⏱️ Mean Time in A&E")
        st.markdown("""
        The **average total time a patient** spends in the department from arrival to departure. This includes:
        - waiting for triage
        - the triage assessment itself
        - waiting for a doctor 
        - treatment
        - for admitted patients, waiting for a ward bed.
        
        Admitted patients consistently have longer times than discharged patients because of the additional wait for a ward bed after the treatment decision 
        is made. This is seen in the patient time distribution chart on the Simulation page
        """)

    st.markdown("")

    with st.container(border=True):
        st.markdown("### 🛏️ Admission Rate")
        st.markdown("""
        The percentage of patients who are **admitted to a ward** rather than discharged home. In this simulation:

        - **Urgent patients** have a **32%** chance of admission 
        - **Non-urgent** patients have a **6%** chance

        "These figures were derived from the dataset — Orange triage patients 
        admit at 32.2% and Green at 5.8%. Overall admission rate is ~14.3%."
        
        A higher admission rate puts more pressure on the department because admitted patients occupy resources for longer while waiting for ward beds
        """)
#AI START
with tab_limitations:
#AI END
    st.subheader("What This Tool Cannot Tell You")

    st.warning("This tool is a proof-of-concept prototype. Please ensure you understand this before acting on any results", icon="⚠️")

    limitations = [
    ("**📈 Results show relative comparison, not precise predictions**",
    "If the simulation shows that adding 2 doctors reduces the breach rate by 10%, the direction of that change is meaningful. The numbers will differ for your hospital"),
    ("**🛏️ This model doesn't account for ward bed shortages**",
    "In reality, a shortage of inpatient beds is one of the reasons for A&E crowding, this tool models a fixed bed wait delay but does not simulate ward capacity constraints"),
    ("**🕐 Staffing levels are constant across 24 hours**",
    "Real departments may run reduced staffing overnight and incraese during peak hours. This simulation represents an average-day rather than specific shift configurations"),
    ("**⚕️ Urgency is modelled as binary**",
     "Patients are classified as urgent (30%) or non-urgent (70%). In reality the NHS uses the five-category Manchester Triage System. This simplification means the model does not capture the full range of clinical acuity"),
    ("**🔬 This is not a substitute for clinical judgement**",
    "It is designed to support exploratory thinking about the relationship between staffing and performance")
    ]
    #AI START
    for title, body in limitations:
        with st.container(border=True):
            st.markdown(f"{title}")
            st.markdown(body)
    #AI END

#AI START
with tab_methodology:
    col_l,col_r = st.columns(2, gap="large")

    with col_l:
        with st.container(border=True):
            st.markdown("### 🗂️ Data Sources")
            st.markdown("""
The simulation is calibrated using a publicly available **synthetic dataset
modelled on University College London Hospitals (UCLH)** NHS Foundation Trust.

Key parameters derived from the data include:
 
- **Arrival rates** — derived rates from datasets and scalled by dividing by 0.126 to estimate total arrivals
- **Triage time distributions** — exponential distribution (mean 10 minutes)
- **Treatment time distributions** — separate distributions for urgent and
  non-urgent patients
- **Admission probabilities** — 32% (urgent) and 6% (non-urgent)
- **Ward-bed wait times** — median delay applied to admitted patients
 
*If you are using this tool for a specific hospital, the model would need
recalibrating with local data to produce meaningful results.*
            """)
    
    with col_r:
        with st.container(border=True):
            st.markdown("### ⚙️ How the Simulation Works")
            st.markdown("""
The model uses **Discrete Event Simulation (DES)** built with
[SimPy](https://simpy.readthedocs.io/). Rather than averaging patient flow,
DES models each patient as an individual entity moving through the department
and competing for shared resources (doctors, nurses).
 
**Patient pathway:**
1. **Arrival** — drawn from a time-varying Poisson process
2. **Triage** — patient waits for a triage nurse; triage duration sampled
   from a fitted distribution
3. **Doctor assessment** — patient waits for an available doctor; treatment
   duration depends on acuity (urgent / non-urgent)
4. **Disposition** — patient is either discharged or, with a probability
   based on acuity, admitted and waits for a ward bed
 
Queues form **naturally** when resources are occupied — waiting times are not
assumed but *emerge* from resource contention. This is what makes the tool
useful for exploring the impact of staffing changes.
            """)
 
        st.markdown("")
 
        with st.container(border=True):
            st.markdown("### 🎯 Calibration")
            st.markdown("""
The model was calibrated by adjusting internal parameters until its baseline
outputs matched the following observed UCLH metrics:
 
| Metricetric | Dataset Target | Simulation Baseline
|---|---|---|
| 4-hour breach rate | 19.9% | 21.6% (CI: 17.5-25.8%) |
| Admission rate | 12.6% | ~14.3% |
| Doctor utilisation | — | ~81% |
Baseline staffing: 6 nurses, 12 doctors
 
Calibration was performed by running repeated simulations and comparing
output distributions against the dataset, rather than by fitting a single
deterministic value.
            """)
#AI END

st.markdown("---")
st.info(
    "This tool is a proof-of-concept prototype developed as a final-year "
    "Computer Science project at City St George's, University of London. "
    "It is not intended for real clinical decision-making.",
    icon="ℹ️"
)
